// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlFm9lhpSogCOKHLZ9e9beSAmq9hFNyt0',
    appId: '1:474328645943:web:36285642f04b4643969ab2',
    messagingSenderId: '474328645943',
    projectId: 'reexam2-c4cd3',
    authDomain: 'reexam2-c4cd3.firebaseapp.com',
    storageBucket: 'reexam2-c4cd3.appspot.com',
    measurementId: 'G-XN92WXKVLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC92lhVA8MWdpcve88l6ksH8GsTpXtlt38',
    appId: '1:474328645943:android:ef547676467f2823969ab2',
    messagingSenderId: '474328645943',
    projectId: 'reexam2-c4cd3',
    storageBucket: 'reexam2-c4cd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcy5S59p5ooZ4HFrSPcaKzGypWrzDJt1E',
    appId: '1:474328645943:ios:b928790775f9a168969ab2',
    messagingSenderId: '474328645943',
    projectId: 'reexam2-c4cd3',
    storageBucket: 'reexam2-c4cd3.appspot.com',
    iosBundleId: 'com.example.reexam2',
  );
}
